import = [
	"~/.config/alacritty/themes/github_dark_high_contrast.toml",
	"~/.config/alacritty/conf/window.toml",
	"~/.config/alacritty/conf/font.toml",
	"~/.config/alacritty/conf/keyboard.toml",
	"~/.config/alacritty/conf/cursor.toml",
]

[colors]
transparent_background_colors = true

[env]
term = "xterm-256color"